### ISSUE TITLE
SignedInState in to new PreviewFactory

### ISSUE THREAD

**Issue by merbula** [aws-amplify/amplify-ui-swift-authenticator#70]
Hi,

Could you please add 'SignedInState' in to PreviewFactory as well?. Then it is possible to use Xcode preview in custom "MainView" implementation too.

Thanks!

**Comment by ruisebas** [comment]
Hi @merbula, thanks for opening this issue.

`SignedInState` is a bit special because it's not really tied up to any of the **Authenticator**'s internal views, so you don't really need the component to provide an "empty" one.

In order for `PreviewFactory` to create one for you, you'd still need to implement your own custom `AuthUser` and `AuthSignOutResult` and provide them to the factory, so it's just simpler and more straightforward for you to just model your `MainView` to use its own state that just wraps the `SignedInState`.

Here's an example:
```swift
// SignedInState protocol
protocol SignedInStateProtocol: ObservableObject {
    var user: AuthUser { get }
    func signOut() async -> AuthSignOutResult
}
extension SignedInState: SignedInStateProtocol {}

// Custom SignedIn State
class MySignedInState: SignedInStateProtocol {
    static var empty = MySignedInState(MockState())

    private var state: any SignedInStateProtocol
    init(_ state: any SignedInStateProtocol) {
        self.state = state
    }

    // Implement the rest by forwarding to SignedInStateProtocol's methods
}

// Custom SignedIn View
struct MySignedInView: View {
    @ObservedObject var state: MySignedInState

    var body: some View { /**/ }
}

// Mocks
struct MockSignOutResult: AuthSignOutResult {}
struct MockedUser: AuthUser {
    var username: String
    var userId: String
}
class MockState: SignedInStateProtocol {
    var user: AuthUser = MockedUser(/**/)
    var signOutResult: AuthSignOutResult =  MockSignOutResult()

    func signOut() async -> AuthSignOutResult {
        return signOutResult
    }
}

// Regular usage
Authenticator { state in
    MySignedInView(state: .init(state))
}

// Preview usage
#Preview {
    MySignedInView(state: .empty)
}
```
The above assumes your main view needs both `user` and `signOut` from `SignedInState`, but if that's not the case you can edit it to better accommodate your use case.
